% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Proyecto Simulacion premisa principal Mujer Bogota Oct\_2024},
  pdfauthor={Denise Bernardo Ferreira},
  pdfkeywords={Estilos de crianza, Tipos de apego, Mujer bogotana},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Proyecto Simulacion premisa principal Mujer Bogota Oct\_2024}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Data analysis notebook}
\author{Denise Bernardo Ferreira}
\date{Friday, November 22, 2024}

\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\section{Introducción}\label{introducciuxf3n}

Este cuaderno implementa el análisis de un modelo de estructura
emocional de la mujer joven adulta universitaria bogotana.

\section{Instalación y carga de
paquetes}\label{instalaciuxf3n-y-carga-de-paquetes}

Se instalan y cargan los paquetes que permiten cargar los datos y
trabajar con modelos de regresión logística ordinal y multinomial:

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"brms"}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"brms"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"ggalluvial"}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"ggalluvial"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"here"}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"here"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"readxl"}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"readxl"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Cargar los datos}\label{cargar-los-datos}

Leemos el archivo de Excel que contiene los datos
MujerBogata\_Data\_Oct\_2024.xlsx.Utilizamos la función \texttt{here}
para llamar los datos desde la carpeta ``Data'' en el working folder.
Este comando carga el archivo en un objeto llamado \texttt{datos}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos }\OtherTok{\textless{}{-}} \FunctionTok{read\_xlsx}\NormalTok{ (}\FunctionTok{here}\NormalTok{(}\StringTok{"Data/MujerBogata\_Data\_Oct\_2024.xlsx"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\section{Transformación de las
variables}\label{transformaciuxf3n-de-las-variables}

A continuación, transformamos los nombres de las variables para
facilitar la visualización en interpretación de los datos:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_trans }\OtherTok{\textless{}{-}}\NormalTok{ datos }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{ARQUETIPO =} \FunctionTok{recode}\NormalTok{(ARQUETIPO, }\StringTok{"1"} \OtherTok{=} \StringTok{\textquotesingle{}Bajo\textquotesingle{}}\NormalTok{, }\StringTok{"2"} \OtherTok{=} \StringTok{\textquotesingle{}Moderado\textquotesingle{}}\NormalTok{, }\StringTok{"3"} \OtherTok{=}  \StringTok{\textquotesingle{}Alto\textquotesingle{}}\NormalTok{ ),}
           \AttributeTok{APEGO =} \FunctionTok{recode}\NormalTok{(APEGO, }\StringTok{"1"} \OtherTok{=} \StringTok{\textquotesingle{}Seguro\textquotesingle{}}\NormalTok{, }\StringTok{"2"} \OtherTok{=} \StringTok{\textquotesingle{}Ansioso\textquotesingle{}}\NormalTok{, }\StringTok{"3"} \OtherTok{=}  \StringTok{\textquotesingle{}Evitativo\textquotesingle{}}\NormalTok{, }\StringTok{"4"} \OtherTok{=} \StringTok{"Desorganizado"}\NormalTok{),}
           \AttributeTok{CRIANZA =} \FunctionTok{recode}\NormalTok{(CRIANZA, }\StringTok{"1"} \OtherTok{=} \StringTok{\textquotesingle{}Autoritario\textquotesingle{}}\NormalTok{, }\StringTok{"2"} \OtherTok{=} \StringTok{\textquotesingle{}Permisivo\textquotesingle{}}\NormalTok{, }\StringTok{"3"} \OtherTok{=}  \StringTok{\textquotesingle{}Negligente\textquotesingle{}}\NormalTok{, }\StringTok{"4"} \OtherTok{=} \StringTok{"Autoritario\_Democratico"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Y nos aseguramos que sean identificados como factores:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convertimos las columnas de interes en factores (nótese que Arquetipo es ordenada)}

\NormalTok{datos\_trans}\SpecialCharTok{$}\NormalTok{ARQUETIPO }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datos\_trans}\SpecialCharTok{$}\NormalTok{ARQUETIPO, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Bajo"}\NormalTok{, }\StringTok{"Moderado"}\NormalTok{, }\StringTok{"Alto"}\NormalTok{), }\AttributeTok{ordered =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{datos\_trans}\SpecialCharTok{$}\NormalTok{APEGO }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datos\_trans}\SpecialCharTok{$}\NormalTok{APEGO, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Seguro"}\NormalTok{, }\StringTok{"Ansioso"}\NormalTok{, }\StringTok{"Evitativo"}\NormalTok{, }\StringTok{"Desorganizado"}\NormalTok{))}
\NormalTok{datos\_trans}\SpecialCharTok{$}\NormalTok{CRIANZA }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(datos\_trans}\SpecialCharTok{$}\NormalTok{CRIANZA, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Autoritario"}\NormalTok{, }\StringTok{"Permisivo"}\NormalTok{, }\StringTok{"Negligente"}\NormalTok{, }\StringTok{"Autoritario\_Democratico"}\NormalTok{))}

\CommentTok{\# Cambioamos los nombres de las columnas (variables)}
\FunctionTok{colnames}\NormalTok{(datos\_trans) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Arquetipo"}\NormalTok{, }\StringTok{"Apego"}\NormalTok{, }\StringTok{"Crianza"}\NormalTok{, }\StringTok{"RegulacionEmocional"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Verificamos que la conversión de los datos fue satisfactoria.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(datos\_trans)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
tibble [400 x 4] (S3: tbl_df/tbl/data.frame)
 $ Arquetipo          : Ord.factor w/ 3 levels "Bajo"<"Moderado"<..: 1 3 2 1 1 3 3 1 1 2 ...
 $ Apego              : Factor w/ 4 levels "Seguro","Ansioso",..: 1 2 2 2 1 3 3 1 2 2 ...
 $ Crianza            : Factor w/ 4 levels "Autoritario",..: 4 3 2 4 4 3 3 4 4 2 ...
 $ RegulacionEmocional: num [1:400] 1 3 3 3 3 1 2 1 1 2 ...
\end{verbatim}

\section{Visualización de los
datos}\label{visualizaciuxf3n-de-los-datos}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{colors }\OtherTok{\textless{}{-}} \FunctionTok{hcl.colors}\NormalTok{(}\DecValTok{4}\NormalTok{, }\StringTok{"dark3"}\NormalTok{)}

\NormalTok{Arquetipo\_Alluvial }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(datos\_trans,}
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{axis1 =}\NormalTok{ Arquetipo, }\AttributeTok{axis2 =}\NormalTok{ Apego, }\AttributeTok{axis3 =}\NormalTok{ Crianza)) }\SpecialCharTok{+}
  \FunctionTok{geom\_alluvium}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ Arquetipo), }\AttributeTok{width =} \DecValTok{1}\SpecialCharTok{/}\DecValTok{5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_stratum}\NormalTok{(}\AttributeTok{width =} \DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{, }\AttributeTok{color =} \StringTok{"grey"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\AttributeTok{stat =} \StringTok{"stratum"}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{after\_stat}\NormalTok{(stratum))) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_discrete}\NormalTok{(}\AttributeTok{limits =} \FunctionTok{c}\NormalTok{(}\StringTok{"Arquetipo"}\NormalTok{, }\StringTok{"Apego"}\NormalTok{, }\StringTok{"Crianza"}\NormalTok{), }\AttributeTok{expand =} \FunctionTok{c}\NormalTok{(.}\DecValTok{05}\NormalTok{, .}\DecValTok{05}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Relacion entre arquetipo, apego y crianza"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Frecuencia"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =}\NormalTok{ colors) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }

\FunctionTok{ggsave}\NormalTok{ (Arquetipo\_Alluvial,}
        \AttributeTok{file =} \FunctionTok{here}\NormalTok{(}\StringTok{"Plots/MujerBogotana\_ArquetipoAlluvial.jpg"}\NormalTok{),}
        \AttributeTok{width =} \DecValTok{15}\NormalTok{,}
        \AttributeTok{height =} \DecValTok{10}\NormalTok{,}
        \AttributeTok{units =} \StringTok{"cm"}\NormalTok{)}

\NormalTok{Arquetipo\_Alluvial}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\includegraphics{MujerBogota_Data_Oct_2024_CodigoR_Analisis_v2_files/figure-pdf/fig-Arquetipo_Alluvial-1.pdf}

}

\caption{\label{fig-Arquetipo_Alluvial}Relación entre el arquetipo, el
apego y la crianza}

\end{figure}%

Figure~\ref{fig-Arquetipo_Alluvial} nos muestra que el apgo al arquetipo
puede estar distribuido dependiendo de el tipo de apego y el estilo de
crianza. Para desentrañar esta relación, emplearemos una regresión
logística.

\section{Modelamiento estadístico}\label{modelamiento-estaduxedstico}

En primer lugar, emplearemos una regresión logística ordinal para
modelar la relación entre el arquetipo (variable oredenada), y apego y
crianza como factores predictores. Utilizaremos el paquete \texttt{brms}
para ajustar el siguiente modelo:

\[
\text{logit}(P(Arquetipo_i \leq k)) = \tau_k - (\beta_1 \times Apego_i + \beta_2 \times Crianza_i)
\] Donde \(P(Arquetipo_i \leq k\) es la probabilidad de la respuesta por
cada observación intre la categoría K o más bajo. \$\tau\_k \$ es el
parámetro para el umbral por categoría \(k\), que representa los límites
entre categorías. \(\beta_1\) es el coeficiente para Apego, indicando el
efecto en una escala de log-odds de ser una categoría inferior.
\(\beta_2\) es el coeficiente para crianza, cuantificado de las misma
manera que para Apego. Este modelo asume probabilidaes (odds)
proporcionales, lo que quiere decir que los prdictores son consistentes
através de todos los umbrales.

\subsection{Ajuste del modelo}\label{ajuste-del-modelo}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Arquetipo\_Mdl1 }\OtherTok{\textless{}{-}} \FunctionTok{bf}\NormalTok{(Arquetipo }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Apego }\SpecialCharTok{+}\NormalTok{ Crianza)}

\FunctionTok{get\_prior}\NormalTok{(Arquetipo\_Mdl1, datos\_trans)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                prior     class                           coef group resp dpar
               (flat)         b                                               
               (flat)         b                   ApegoAnsioso                
               (flat)         b             ApegoDesorganizado                
               (flat)         b                 ApegoEvitativo                
               (flat)         b CrianzaAutoritario_Democratico                
               (flat)         b              CrianzaNegligente                
               (flat)         b               CrianzaPermisivo                
 student_t(3, 0, 2.5) Intercept                                               
 student_t(3, 0, 2.5)     sigma                                               
 nlpar lb ub       source
                  default
             (vectorized)
             (vectorized)
             (vectorized)
             (vectorized)
             (vectorized)
             (vectorized)
                  default
        0         default
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Arquetipo\_Fit1 }\OtherTok{\textless{}{-}}
  \FunctionTok{brm}\NormalTok{(}
    \AttributeTok{data =}\NormalTok{ datos\_trans,}
    \AttributeTok{family =} \StringTok{"cumulative"}\NormalTok{,}
    \AttributeTok{formula =}\NormalTok{ Arquetipo\_Mdl1,}
    \AttributeTok{chains =} \DecValTok{4}\NormalTok{,}
    \AttributeTok{cores =} \DecValTok{4}\NormalTok{,}
    \AttributeTok{warmup =} \DecValTok{2500}\NormalTok{,}
    \AttributeTok{iter =} \DecValTok{5000}\NormalTok{,}
    \AttributeTok{seed =} \DecValTok{8807}\NormalTok{,}
    \AttributeTok{control =} \FunctionTok{list}\NormalTok{(}\AttributeTok{adapt\_delta =} \FloatTok{0.99}\NormalTok{, }\AttributeTok{max\_treedepth =} \DecValTok{15}\NormalTok{),}
    \AttributeTok{file =} \FunctionTok{here}\NormalTok{(}\StringTok{"Models/MujerBogotana\_Arquetipo\_Fit1.rds"}\NormalTok{),}
    \AttributeTok{file\_refit =} \StringTok{"never"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

A continuación vemos la tabla de resultados:

\section{Tabla de resultados}\label{tabla-de-resultados}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(Arquetipo\_Fit1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 Family: cumulative 
  Links: mu = logit; disc = identity 
Formula: Arquetipo ~ Apego + Crianza 
   Data: datos_trans (Number of observations: 400) 
  Draws: 4 chains, each with iter = 5000; warmup = 2500; thin = 1;
         total post-warmup draws = 10000

Regression Coefficients:
                               Estimate Est.Error l-95% CI u-95% CI Rhat
Intercept[1]                       0.82      0.33     0.18     1.48 1.00
Intercept[2]                       3.38      0.39     2.64     4.18 1.00
ApegoAnsioso                       3.31      0.37     2.60     4.04 1.00
ApegoEvitativo                     3.27      0.43     2.45     4.14 1.00
ApegoDesorganizado                 3.57      0.50     2.58     4.55 1.00
CrianzaPermisivo                   0.08      0.31    -0.53     0.70 1.00
CrianzaNegligente                  0.21      0.27    -0.32     0.73 1.00
CrianzaAutoritario_Democratico    -3.61      0.51    -4.65    -2.68 1.00
                               Bulk_ESS Tail_ESS
Intercept[1]                       5191     5684
Intercept[2]                       4246     5903
ApegoAnsioso                       4228     5103
ApegoEvitativo                     4639     6055
ApegoDesorganizado                 4862     5431
CrianzaPermisivo                   6689     6144
CrianzaNegligente                  6565     6863
CrianzaAutoritario_Democratico     6403     5683

Further Distributional Parameters:
     Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
disc     1.00      0.00     1.00     1.00   NA       NA       NA

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
\end{verbatim}

De la tabla nos interesan los coeficientes para Apego y crianza. En
primer lugar, los resultados indican que las probabilidades (odds) de
que el apego ansioso genere una mayor categoría de arquetipo es 3.31
(95\% = 2.60 to 4.04). La situación es análoga para el apego evitativo
(3.27, 95\% CI = 2.45 to 4.14) y apego desorganizado (3.57, 95\% CI =
2.58 to 4.55). En este sentido, el apego segura esta estrechamente
relacionado con un apego al arquetipo bajo.

Por otra parte, los resultados indican que la crianza permisiva no tiene
un impacto sustancial sobre la probabilidad de un incremento en el
arquetipo (0.08, 95\% CI= -0.53 to 0.70), al igual que la crianza
negligente (0.21, 95\% CI= -0.32 to 0.73). No obstante, la crianza
autoritaria/democrática parece tener un efecto negativo en la
probabilidad (odds) de un tipo de arquetipo más alto (-3.61, 95\% cI =
-4.65 to -2.68).

En conjunto, los resultados sugieren que el estilo de apego tiene una
relación diracto con un incremento en el tipo de arquetipo, con el apego
desorganizado teniendo el impacto más alto. Por el contrario, los
estilos de crianza tiene impactos más sutiles o inexistentes, con el
estilo autoritorio/democrático reducingdo la probabilidad (odds) de un
incremento en el apego. Ahora visualizemos los resultados en gráficos.

\section{Visualización de
resultados}\label{visualizaciuxf3n-de-resultados}

En primer lugar, evidenciamos el efecto de del apego en la deficinicón
del arquetipo:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Arquetipo\_Apego\_CE }\OtherTok{\textless{}{-}} \FunctionTok{conditional\_effects}\NormalTok{(Arquetipo\_Fit1, }\StringTok{"Apego"}\NormalTok{, }\AttributeTok{categorical =} \ConstantTok{TRUE}\NormalTok{) }

\NormalTok{Arquetipo\_Apego\_Fig }\OtherTok{\textless{}{-}} \FunctionTok{plot}\NormalTok{(Arquetipo\_Apego\_CE, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)[[}\DecValTok{1}\NormalTok{]]}

\NormalTok{Arquetipo\_Apego\_Fig }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Effects del tipo de apego en el arquetipo"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Probabilidad"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Tipo de apego"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\includegraphics{MujerBogota_Data_Oct_2024_CodigoR_Analisis_v2_files/figure-pdf/fig-Arquetipo_CE_Apego-1.pdf}

}

\caption{\label{fig-Arquetipo_CE_Apego}Effecto del apego en el
arquetipo}

\end{figure}%

El gráfico nos muestra que mujeres con apego seguro presentan una baja
probabilidad de un arquetipo alto y se encuentra fuertemente relacionado
con un bajo apego al arquetipo. Puede observarse también que las
probabilidades para un arquetipo moderado y alto son similares para los
estilos de crianza ansioso, evitativo y desorganizado.

A continuación, visualizamos de forma análoga el efecto de la crianza:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Arquetipo\_Crianza\_CE }\OtherTok{\textless{}{-}} \FunctionTok{conditional\_effects}\NormalTok{(Arquetipo\_Fit1, }\StringTok{"Crianza"}\NormalTok{, }\AttributeTok{categorical =} \ConstantTok{TRUE}\NormalTok{) }

\NormalTok{Arquetipo\_Crianza\_Fig }\OtherTok{\textless{}{-}} \FunctionTok{plot}\NormalTok{(Arquetipo\_Crianza\_CE, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)[[}\DecValTok{1}\NormalTok{]]}

\NormalTok{Arquetipo\_Crianza\_Fig }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Effects del tipo de crianza en el arquetipo"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Probabilidad"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Tipo de apego"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

\centering{

\includegraphics{MujerBogota_Data_Oct_2024_CodigoR_Analisis_v2_files/figure-pdf/fig-Arquetipo_CE_Crianza-1.pdf}

}

\caption{\label{fig-Arquetipo_CE_Crianza}Effecto del apego en el
arquetipo}

\end{figure}%

Por el contrario, puede apreciarse que el tipo de apego no posee efectos
sustanciales en el apego al arquetipo. En todos, los casos, la mayor
probabilidad para cualquier tipo de crianza es un arquetipo bajo,
especialmente en el tipo autoritario/democrático.




\end{document}
